display_name: LightingSend
packager: Tienisto
packagerEmail: dev.tien.donam@gmail.com
url: https://github.com/Mutantcat-Working-Group/LightningSend
buildArch: x86_64
license: MIT

icon: assets/img/logo-512.png

requires:
  - libappindicator
  - xdg-user-dirs

keywords:
  - Sharing
  - LAN
  - Files

generic_name: An open source cross-platform alternative to AirDrop
summary: Share files easily with LightingSend
group: Applications/Utilities

categories:
  - GTK
  - FileTransfer
  - Utility

startup_notify: true
