name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish LightingSend
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: LightingSend.LightingSend
          installers-regex: 'LightingSend-(?!CLI-).*\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
      - name: Publish LightingSend CLI
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: LightingSend.LightingSend.CLI
          installers-regex: 'LightingSend-CLI-.*\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
